#!/bin/bash
#SBATCH --nodes=1
#SBATCH --time=3-00:00:00
#SBATCH --partition=comp72
#SBATCH --ntasks=32       #number of cpus to use
#SBATCH --job-name=RepeatMasker
#SBATCH --mail-user=pedrohenriquepezzi@gmail.com
#SBATCH --mail-type=ALL
#SBATCH --output=/scrfs/storage/ppezzi/GC3F_Afasciculata/Assembly_Afasciculata/annotation/repeatmasker/RepeatMasker_Agalinis.%j.out

#Display the job context
echo Job: $SLURM_JOB_NAME with ID $SLURM_JOB_ID
echo Running on `hostname`
echo Job started at `date +"%T %a %d %b %Y"`
echo Directory is `pwd`
echo Using $SLURM_NTASKS processors across $SLURM_NNODES nodes

#Assign path variables
WD=/scrfs/storage/ppezzi/GC3F_Afasciculata/Assembly_Afasciculata/annotation/repeatmasker
GENOME=/scrfs/storage/ppezzi/GC3F_Afasciculata/Assembly_Afasciculata/annotation/Agalinis_fasciculata_159scaffolds_final_renamed_sorted.fasta
THREADS=32

#Enter directory
cd $WD

#Load modules
module purge
module load python
source /home/ppezzi/.bashrc
conda activate repeatmasker

#concatenate known and `unknown` repeats
cat Agalinis-families.prefix.fa.known.FINAL Agalinis-families.prefix.fa.unknown.FINAL > Agalinis-families.prefix.fa.known.unknown.FINAL

#run repeatmasker
RepeatMasker -pa $THREADS -gff -s -a -inv -no_is -norna -xsmall -nolow -div 40 -lib Agalinis-families.prefix.fa.known.unknown.FINAL -cutoff 225 $GENOME

#OPTIONAL - calculate the kimura distance
perl /scrfs/storage/ppezzi/home/.conda/envs/repeatmasker/share/RepeatMasker/util/calcDivergenceFromAlign.pl -s ${GENOME}.align.divsum ${GENOME}.align
tail -n 72 ${GENOME}.align.divsum > ${GENOME}.Kimura.distance

#OPTIONAL - generate a modified GFF file, which I like more than the default generated by RepeatMasker.
python AdjustGFF_new.py ${GENOME}.out.gff Agalinis-families.prefix.fa.known.unknown.FINAL ${GENOME}.out.adjusted.gff

# Final time stamp
echo Job finished at `date +"%T %a %d %b %Y"`
